steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'FnComputePricelistHistories',
      '--runtime', 'go111',
      '--trigger-http',
      '--source', './app',
      '--memory', '512M',
      '--region', 'us-central1',
      '--timeout', '120s'
    ]